import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Wallet } from '../components/hooks/Wallet'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Test App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Wallet>
          {children}
        </Wallet>
      </body>
    </html>
  )
}
